[package]
name = "ldk-node-workshop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ldk-node = "0.1.0"
bdk = { version = "=0.28.0", default-features = false }
